Error installing requirements
This error occurs while installing:

  error: /usr/local/lib/python2.7/dist-packages/_mysql.so: Permission denied

Trying to give Travis CI some sudo powers as demonstrated here:
http://docs.travis-ci.com/user/installing-dependencies/

Also the option, `--use-mirrors`, is deprecated. Ignoring this option
for now. May consider later.